Open (Bug) Server logs missing request id and throw exception
GoodDollar/GoodServer pull request #251
Opened 2020-09-10 12:45 UTC by serdiukov-o-nordwhale

# Description

- restored request uuid logs output
- added possible fix for uncaught "TypeError: Cannot read property 'error' of undefined"

About #250 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [x] PR title matches follow: (Feature|Bug|Chore) Task Name
- [x] My code follows the style guidelines of this project
- [x] I have followed all the instructions described in the initial task (check Definitions of Done)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have added reference to a related issue in the repository
- [x] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [x] @mentions of the person or team responsible for reviewing proposed changes

2020-09-11 07:47 UTC, yaroslav-fedyshyn-nordwhale approved these changes

2020-09-13 10:30 UTC, sirpy commented
@serdiukov-o-nordwhale leave the only the uuid and log format fixes
issue is with blockchain txs

2020-09-13 10:31 UTC, sirpy requested changes
leave only uuid and log fixes

2020-09-14 10:22 UTC, serdiukov-o-nordwhale commented
@sirpy Done

2020-09-15 13:08 UTC, merged