Dont block user on mautic
GoodDollar/GoodServer pull request #313
Opened 2021-02-18 09:16 UTC by sirpy

# Description
during signup we block until data is updated in mautic/database etc this is not critical for user, so i've removed blocking

- dont block on user signup
- removed topwallet form signup (user now uses the faucet contract through app)
- removed temp mautic contact creation on verify email, no longer required since we send through SES

QA
- check user signup is working as expected
- new user doesnt have gas issue
- verify email step in signup(with passwordless) and when editing on profile works fine and also updates the user email on mautic correctly

2021-02-18 10:57 UTC, serdiukov-o-nordwhale requested changes

2021-02-18 10:57 UTC, serdiukov-o-nordwhale commented on src/server/utils/timeout.js
> +Promise.timeout = (promises, timeout, timeoutReason) =>
1. do not need to make it 'universal', let it just receives some promise. If someone would need pass array of promises, he would wrap it to Promise.all by himself
2. we probably may want to use it with retry(). So let pass not a promise itself but the async function returning promise
3. Modifying existing JS objects is a kind of the bad design. it should be used only if we want to polyfill some spec which doesn't exists on the JS engine we're using.

Following the pt 1-3 i suggest to usethe implementation below:

```javascript
export const runWithTimeout(asyncFn, millis, timeoutReason = null) =>
  Promise.race([asyncFn(), requestTimeout(millis, timeoutReason)])
```

2021-02-18 13:21 UTC, serdiukov-o-nordwhale commented
abouts pt2 - ok let's fix when we'll need that
but pt3 should be fixed as it's really bad design. Promise interface is strongly defined: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
There's no Promise.timeout, so we shouldn't polyfill that method. If you don't like runWithTimeout name - you could choose your own

2021-02-22 11:38 UTC, serdiukov-o-nordwhale commented
@sirpy  how about pt3 ? would you fix it ? i really recommend to do that because changing generic interfaces is a bad idea

2021-02-22 14:06 UTC, sirpy commented
you can modify it if you want.
i dont think it is that important, many libraries extend interfaces

2021-02-23 10:04 UTC, serdiukov-o-nordwhale commented
> you can modify it if you want. i dont think it is that important, many libraries extend interfaces

yes, this was popular some time ago. But after HTML5 standard was released, the concept was changed to keep the existing interfaces.
From the all languages/frameworks/etc i met last time i saw 'extension' feature only in the Swift. But Swift doesn't just extends some class with some method. You have define protocol (it's like interface in Java) firstly then add extension for conform that protocol. So the interface segregation principle isn't breaking here.

2021-02-23 10:35 UTC, serdiukov-o-nordwhale approved these changes

2021-02-23 10:41 UTC, sirpy commented on src/server/storage/storageAPI.js
> +        withTimeout(signUpPromises, 30000, 'signup promises timeout')
```suggestion
        withTimeout(Promise.all(signUpPromises), 30000, 'signup promises timeout')
```

2021-02-23 10:42 UTC, merged

2021-03-01 11:35 UTC, iLystopad commented
@sirpy The user is not able to sign up with passwordless. 
{from: "SignupState"} "New user failure" "User email not verified!" E8: User email not verified! is displayed in the console after the user clicking on the "Let's start" button

Checked on the QA 1.23.1-1
Device: Desktop // Windows 10 // Chrome 88.0.4324.150

Attachment: 
![image.png](https://images.zenhubusercontent.com/5fe99267688d8a03d64eabd2/0b0e1595-ad53-4137-bcf4-4c8d857aa6a9)

2021-03-01 11:44 UTC, iLystopad commented
@sirpy 
"Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bok%2C%20error%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings" is displayed in the console after entering invalid verification code on email verification page

Checked on the QA 1.23.1-1
Device: Desktop // Windows 10 // Chrome 88.0.4324.150

Note: Also reproduced after editing email and entering invalid verification code on the Edit Profile page

Attachment: 
![image.png](https://images.zenhubusercontent.com/5fe99267688d8a03d64eabd2/c1663a87-7cd0-4876-9d0d-4ec112d95999)

2021-03-01 19:33 UTC, sirpy commented
@iLystopad try now

2021-03-02 09:52 UTC, iLystopad commented
@sirpy The issue with signup via passwordless is still reproduced. The issue with entering an invalid verification code is fixed.

The user is not able to sign up with passwordless.
{from: "SignupState"} "New user failure" "User email not verified!" E8: User email not verified! is displayed in the console after the user clicking on the "Let's start" button

Checked on the QA 1.23.1-2
Device: Desktop // Windows 10 // Chrome 88.0.4324.150

Attachment:
Video: https://www.dropbox.com/s/9m8vctxdz4scpr6/The%20issue%20with%20sign%20up%20with%20passwordless.mp4?dl=0
![image.png](https://images.zenhubusercontent.com/5fe99267688d8a03d64eabd2/5aeb704e-711d-4483-bee3-8266b1f4108d)