Ongage
GoodDollar/GoodServer pull request #353
Opened 2022-01-27 10:14 UTC by sirpy

# Description
- removed mautic
- switched to using ongage

About #351

2022-01-28 14:01 UTC, johnsmith-gooddollar requested changes

2022-01-28 14:01 UTC, johnsmith-gooddollar commented on src/server/crm/ongage.js
> +    const { baseUrl, log } = this
if you will use axios, you won't need this method.
you could create axios intsance and configure all this stuff with request / response / error handlers
then just call .get / .post etc of `this.axios`

2022-01-28 14:01 UTC, johnsmith-gooddollar commented on src/server/verification/verificationAPI.js
> +import { OnGageAPI } from '../crm/ongage'
maybe rename it to `Ongage`

2022-01-30 11:32 UTC, sirpy commented on src/server/crm/ongage.js
> +    this.baseHeaders = {
ok. can you implement all your suggested changes?

2022-01-31 15:50 UTC, johnsmith-gooddollar commented on src/server/crm/ongage.js
> +    this.baseHeaders = {
ok

2022-01-31 18:37 UTC, johnsmith-gooddollar commented on src/server/crm/ongage.js
> +export const parseUtmString = utmString => {
done

2022-01-31 18:37 UTC, johnsmith-gooddollar commented on src/server/crm/ongage.js
> +    const { baseUrl, log } = this
done

2022-01-31 18:37 UTC, johnsmith-gooddollar commented on src/server/verification/verificationAPI.js
> +import { OnGageAPI } from '../crm/ongage'
done

2022-01-31 18:38 UTC, johnsmith-gooddollar approved these changes

2022-02-01 08:22 UTC, sirpy commented on src/server/crm/ongage.js
> +      timeout: 15000,
```suggestion
      timeout: 3000,
```

2022-02-01 08:54 UTC, sirpy commented
@johnsmith-gooddollar tests no longer pass

2022-02-01 13:32 UTC, johnsmith-gooddollar commented
> @johnsmith-gooddollar tests no longer pass

fixed

2022-02-11 15:54 UTC, johnsmith-gooddollar commented
test were added, everything checked
ready to merge after new signup release

2022-02-22 10:28 UTC, merged