fv v2 identifier
GoodDollar/GoodServer pull request #416
Opened 2023-03-20 13:46 UTC by sirpy

# Description
Verify correctly new format of FV identifiers that are tied to the whitelisted address

2023-03-20 17:36 UTC, johnsmith-gooddollar requested changes

2023-03-20 17:36 UTC, johnsmith-gooddollar commented on src/server/verification/verificationAPI.js
> +const verifyFVIdentifier = async (identifier, gdAddress) => {
this should be moved to src/server/verification/utils

2023-03-20 17:36 UTC, johnsmith-gooddollar commented on src/server/verification/verificationAPI.js
> +      const { params, log, user, query } = req
see suggestions from above

2023-03-20 17:36 UTC, johnsmith-gooddollar commented on src/server/verification/verificationAPI.js
> +        await verifyFVIdentifier(enrollmentIdentifier, gdAddress)
middleware from example could be also usable here

2023-03-21 08:04 UTC, sirpy commented on src/server/verification/verificationAPI.js
> +        let v2Identifier = enrollmentIdentifier.slice(0, 42)
overkill

2023-04-13 15:58 UTC, merged